apiVersion: v1
kind: Service
metadata:
  name: phillip-simple-autos-lb
spec:
  type: LoadBalancer
  selector:
    app: phillip-simple-autos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http