apiVersion: apps/v1
kind: Deployment
metadata:
  name: phillip-simple-autos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phillip-simple-autos
  template:
    metadata:
      labels:
        app: phillip-simple-autos
    spec:
      containers:
        - image: $IMAGE
          name: phillip-simple-autos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: 52.26.72.203
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: super-secret-db-token
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: super-secret-db-token
                  key: db_user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: super-secret-db-token
                  key: db_pwd
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: super-secret-deploy-token